config/routes.rb
Rails.application.routes.draw do
  get "oauths/oauth"
  get "oauths/callback"
  # トップページのルーティング
  root 'welcome#index'

  # ユーザーセッションのルーティング
  get '/login', to: 'sessions#new', as: :login
  post '/login', to: 'sessions#create', as: :create_session
  delete '/logout', to: 'users#destroy', as: :logout


  resources :users, only: [:new, :create, :show, :edit, :update]
  get '/menu', to: 'menu#index', as: :menu
  resource :account, only: [:show, :edit, :update], controller: 'users'
  resources :recipes, only: [:new, :create, :show, :index, :edit, :update, :destroy] do
    collection do
      get :search
    end
  end

  # Google OAuth のログイン
  get '/auth/google_oauth2/callback', to: 'sessions#create'
  get '/auth/failure', to: redirect('/')

  post "/oauth/callback"
  get '/auth/:provider/callback', to: 'sessions#google_oauth2'
  get '/auth/failure', to: 'sessions#new' # 認証失敗時のリダイレクト



  # その他のルーティング
  get 'home/index', to: 'home#index', as: :home
  get '/confirm_email', to: 'users#confirm_email', as: :confirm_email

  get '/favicon.ico', to: proc { [204, {}, []] }

end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  self.primary_key = 'uuid'
  has_many :recipes, dependent: :destroy, foreign_key: 'user_uuid'
  has_many :sns_credentials, dependent: :destroy
  accepts_nested_attributes_for :sns_credentials

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, confirmation: true, length: { minimum: 6 }, if: :password_required?
  validates :remember_me_token, uniqueness: true, allow_nil: true

  # OAuthトークンのリフレッシュ
  def refresh_access_token!
    return unless refresh_token && (token_expires_at.nil? || token_expires_at < Time.current)

    client = OAuth2::Client.new(
      ENV['GOOGLE_CLIENT_ID'],
      ENV['GOOGLE_CLIENT_SECRET'],
      site: 'https://oauth2.googleapis.com',
      token_url: '/token'
    )
    token = OAuth2::AccessToken.new(client, access_token, refresh_token: refresh_token)

    refreshed_token = token.refresh!

    update!(
      access_token: refreshed_token.token,
      refresh_token: refreshed_token.refresh_token || refresh_token,
      token_expires_at: Time.at(refreshed_token.expires_at)
    )
  rescue OAuth2::Error => e
    Rails.logger.error "Failed to refresh token: #{e.message}"
    nil
  end

  # OAuthユーザーの検索または作成
  def self.find_or_create_for_oauth(auth)
    user = find_or_initialize_by(provider: auth.provider, uid: auth.uid)
    if user.new_record?
      user.email = auth.info.email
      user.name = auth.info.name
      user.password = SecureRandom.hex(16) # 仮パスワード
      user.save!
    end
    user
  end

  private

  def password_required?
    provider.blank? && uid.blank?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  before_action :require_login, except: [:new, :create]


  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.uuid  # Sorceryを使ったログイン
      Rails.logger.debug "Session[:user_id] before redirect: #{session[:user_id]}"
      redirect_to home_path, notice: "ユーザー登録が完了しました"
      Rails.logger.debug "Session[:user_id] in home#index: #{session[:user_id]}"
    else
      flash.now[:alert] = @user.errors.full_messages.join(", ")
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to account_path, notice: "プロフィールが更新されました"
    else
      flash.now[:alert] = "更新に失敗しました"
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "ログアウトしました"
  end

  # Google OAuthのコールバック用
  def oauth
    user = User.from_google(request.env["omniauth.auth"])
    
    if user.persisted?
      # ログインしてユーザーをセッションに設定
      session[:user_id] = user.id
      redirect_to home_path, notice: "ログインしました！"
    else
      # ユーザーを新規作成
      redirect_to new_user_path, alert: "Googleアカウントでのログインに失敗しました。"
    end
  end

  private

  def set_user
    @user = current_user
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def omniauth_failure
    redirect_to init_sign_in_users_path
    #redirect wherever you want.
  end
end

app/views/users/edit.html.erb
<h1>プロフィール編集</h1>

<%= form_for @user, url: account_path, method: :put do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>

  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <% if @user.errors.any? %>
    <div class="alert alert-danger">
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div>
    <%= f.submit "更新する" %>
  </div>
<% end %>

<%= link_to '戻る', account_path, style: 'text-decoration: none;' %>

app/views/users/new.html.erb
<div class="container mt-5">
  <h1>新規登録</h1>

  <%= form_with model: @user, url: users_path, local: true do |f| %>
    <% if @user.errors.any? %>
      <div class="alert alert-danger">
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <%= f.label :name, "名前" %>
      <%= f.text_field :name %>
    </div>

    <div>
      <%= f.label :email, "メールアドレス" %>
      <%= f.email_field :email %>
    </div>

    <div>
      <%= f.label :password, "パスワード" %>
      <%= f.password_field :password %>
    </div>

    <div>
      <%= f.label :password_confirmation, "パスワード（確認）" %>
      <%= f.password_field :password_confirmation %>
    </div>

    <%= f.submit "登録" %>
  <% end %>

  <!-- Googleログインボタンの表示 -->
  <div id="g_id_onload"
       data-client_id="<%= ENV['GOOGLE_CLIENT_ID'] %>"
       data-login_uri="http://localhost:3000/auth/google_oauth2/callback"
       data-auto_prompt="false">
  </div>
  <div class="g_id_signin"
       data-type="standard"
       data-size="large"
       data-theme="outline"
       data-text="sign_in_with"
       data-shape="rectangular"
       data-logo_alignment="left">
  </div>

  <div class="text-center mt-3">
    <%= link_to "ログインはこちら", login_path %>
  </div>
</div>

app/views/users/show.html.erb
<h1>アカウント</h1>

<p><strong>ユーザー名:</strong> <%= @user.name %></p>
<p><strong>メールアドレス:</strong> <%= @user.email %></p>

<%= link_to 'プロフィール編集', edit_account_path, style: 'text-decoration: none; color: black;' %>
<%= button_to 'ログアウト', logout_path, method: :delete, style: 'background: none; border: none; color: black; text-decoration: underline;' %>