config/routes.rb
Rails.application.routes.draw do
  get "oauths/oauth"
  get "oauths/callback"
  # トップページのルーティング
  root 'welcome#index'

  # ユーザーセッションのルーティング
  get '/login', to: 'sessions#new', as: :login
  post '/login', to: 'sessions#create', as: :create_session
  delete '/logout', to: 'users#destroy', as: :logout


  resources :users, only: [:new, :create, :show, :edit, :update]
  get '/menu', to: 'menu#index', as: :menu
  resource :account, only: [:show, :edit, :update], controller: 'users'
  resources :recipes, only: [:new, :create, :show, :index, :edit, :update, :destroy] do
    collection do
      get :search
    end
  end

  # Google OAuth のログイン
  get '/auth/google_oauth2/callback', to: 'sessions#create'
  get '/auth/failure', to: redirect('/')

  post "/oauth/callback"
  get '/auth/:provider/callback', to: 'sessions#google_oauth2'
  get '/auth/failure', to: 'sessions#new' # 認証失敗時のリダイレクト



  # その他のルーティング
  get 'home/index', to: 'home#index', as: :home
  get '/confirm_email', to: 'users#confirm_email', as: :confirm_email

  get '/favicon.ico', to: proc { [204, {}, []] }

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    @recipes = Recipe.where(user_id: current_user.id) if current_user
    @recipes ||= []  # もし@recipesがnilの場合に空の配列を設定
  end

  private

  def authenticate_user!
    unless session[:user_id]
      redirect_to login_path
    end
  end
end

app/views/home/index.html.erb
<%= content_for :title, "レシピ一覧 | My Recipe" %>
<div class="container">
  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <h1>my-recipes</h1>

      <!-- 検索フォーム -->
      <%= form_with url: recipes_path, method: :get, local: true do %>
        <div class="mb-3">
          <%= text_field_tag :query, params[:query], placeholder: 'キーワードを入力...', class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= submit_tag "検索", class: "btn btn-primary" %>
        </div>
      <% end %>

      <!-- 検索結果表示 -->
      <% if @recipes.any? %>
        <ul class="list-group">
          <% @recipes.each do |recipe| %>
            <li class="list-group-item">
              <%= link_to recipe.title, recipe_path(recipe) %>
            </li>
          <% end %>
        </ul>
      <% else %>
        <p>まだレシピがありません</p>
      <% end %>

      <!-- レシピ作成リンク -->
      <%= link_to 'レシピを作成する', new_recipe_path, class: 'btn btn-primary mt-3' %>
    </div>
  </div>
</div>