config/routes.rb
Rails.application.routes.draw do
  get "oauths/oauth"
  get "oauths/callback"
  # トップページのルーティング
  root 'welcome#index'

  # ユーザーセッションのルーティング
  get '/login', to: 'sessions#new', as: :login
  post '/login', to: 'sessions#create', as: :create_session
  delete '/logout', to: 'users#destroy', as: :logout


  resources :users, only: [:new, :create, :show, :edit, :update]
  get '/menu', to: 'menu#index', as: :menu
  resource :account, only: [:show, :edit, :update], controller: 'users'
  resources :recipes, only: [:new, :create, :show, :index, :edit, :update, :destroy] do
    collection do
      get :search
    end
  end

  # Google OAuth のログイン
  get '/auth/google_oauth2/callback', to: 'sessions#create'
  get '/auth/failure', to: redirect('/')

  post "/oauth/callback"
  get '/auth/:provider/callback', to: 'sessions#google_oauth2'
  get '/auth/failure', to: 'sessions#new' # 認証失敗時のリダイレクト



  # その他のルーティング
  get 'home/index', to: 'home#index', as: :home
  get '/confirm_email', to: 'users#confirm_email', as: :confirm_email

  get '/favicon.ico', to: proc { [204, {}, []] }

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    # トップページ用のアクション
  end
end

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <title><%= t('welcome.title') %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  
  <!-- Bootstrap CSS を読み込み -->
  
  
  <!-- 必要なJSファイルを読み込み -->
  <%= javascript_include_tag 'application', 'data-turbo-track': 'reload', type: 'module' %>
  
  <!-- Material Icons -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>
  <main class="container text-center mt-5">
    <div class="welcome-main">
      <h1 class="welcome-text"><%= t('welcome.title') %></h1>
      <p class="welcome-text"><%= t('welcome.subtitle') %></p>
      <div class="button-container mt-4">
        <%= link_to t('welcome.new_user'), new_user_path, class: "btn btn-primary me-2" %>
        <%= link_to t('welcome.login'), login_path, class: "btn btn-secondary" %>
      </div>
    </div>

    <!-- トップページ画像 -->
    <%= image_tag "top.png", alt: "welcomeイメージ", class: 'top-image img-fluid mt-4' %>
  </main>
</body>
</html>