config/routes.rb
Rails.application.routes.draw do
  get "oauths/oauth"
  get "oauths/callback"
  # トップページのルーティング
  root 'welcome#index'

  # ユーザーセッションのルーティング
  get '/login', to: 'sessions#new', as: :login
  post '/login', to: 'sessions#create', as: :create_session
  delete '/logout', to: 'users#destroy', as: :logout


  resources :users, only: [:new, :create, :show, :edit, :update]
  get '/menu', to: 'menu#index', as: :menu
  resource :account, only: [:show, :edit, :update], controller: 'users'
  resources :recipes, only: [:new, :create, :show, :index, :edit, :update, :destroy] do
    collection do
      get :search
    end
  end

  # Google OAuth のログイン
  get '/auth/google_oauth2/callback', to: 'sessions#create'
  get '/auth/failure', to: redirect('/')

  post "/oauth/callback"
  get '/auth/:provider/callback', to: 'sessions#google_oauth2'
  get '/auth/failure', to: 'sessions#new' # 認証失敗時のリダイレクト



  # その他のルーティング
  get 'home/index', to: 'home#index', as: :home
  get '/confirm_email', to: 'users#confirm_email', as: :confirm_email

  get '/favicon.ico', to: proc { [204, {}, []] }

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>my-recipe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= favicon_link_tag 'favicon.ico' %>
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
    <%= javascript_include_tag "application", type: "module", "data-turbo-track": "reload" %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script src="https://accounts.google.com/gsi/client" async defer></script>
  </head>

  <body>
    <header style="display: flex; justify-content: space-between; align-items: center; padding: 10px; background-color: #EEFFFF; border-bottom: 1px solid #ddd;">
      <div style="display: flex; align-items: center;">
        <%= link_to (current_user ? home_path : root_path) do %>
          <%= image_tag 'diary.png', alt: 'Diary', style: 'height: 40px; margin-right: 10px;' %>
        <% end %>
        <h1 style="font-size: 20px; margin: 0;">my-recipe</h1>
      </div>

      <div style="display: flex; align-items: center; gap: 20px;">
        <% if current_user %>
          <%= link_to '<span class="material-icons">add</span>'.html_safe, new_recipe_path, style: 'text-decoration: none; color: black;' %>
          <%= link_to '<span class="material-icons">menu</span>'.html_safe, menu_path, style: 'text-decoration: none; color: black;' if current_user %>
        <% end %>
      </div>
    </header>

    

    <main style="padding: 20px;">
      <%= yield %>
    </main>
  </body>
</html>